env:
  global:
  # Docker REGsitory
  - REG=fjudith/alfresco
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - REPO=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "repository"; else echo ${TRAVIS_BRANCH}-repository ; fi`
  - OOO=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "libreoffice"; else echo ${TRAVIS_BRANCH}-libreoffice ; fi`
  - SEARCH=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "search"; else echo ${TRAVIS_BRANCH}-search ; fi`
  - SHA=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "share"; else echo ${TRAVIS_BRANCH}-share ; fi`

  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "AtgApfmFvraJGB37hCUlbdzZqJeamBu5u268p16uD9zP3OnzgiLCKoesHeFK45X6zAS68GDv1X3TCCiuNr+X5WP0U5rBDQubAXN753rc+ipuyaUrz5YliOVWEWlFAWBUxBHKX4Nk+wWcMKa2Xo3qbpHfhZh8fIU87Jhg4yOP7MYEOsWEQ5ifxUkQgAd9QLrZnnSDIkeTFgfBsCrfDv0/cryA6PmBze5HcD1vJvtg3OK5PUVUb1Aj1UlvQF1b6MjH086mQTrFdKCrnwTWcgJdB99tIVoS2rQplSMaBqWJc6Mve6k/vHdZzU3ZaFwlkYuVD1MFuEuRSAibImuXLF+opQ3NJgriOLgOkEHobG+p4FRPaBlIwkwty2aelLUXHhAiNgFtclg5bIjnOMRx+IY+tDO8qRX2W0mLx3Z8OpkqdN7om3s8SPE6qBIyYZd81zZw5cdtWtyjEMC0EZFEmIiftjBDbmAIg00A+jyoGnMqaXS+RbMzfV7xg+sh5wiM6w/58r6GbUnCzVN0HLwgQYo8ThXE6tTVMFmK9gV/8+aJQTXhSTAyfAdTx/YRfFGFrZk2QJX+r+a9X36u9Ee9x2ODZphkC0RFYdPPeUxf9CsV8lN3g58bMtkZekw78qeY2sDEv3NE5gVYyuzgmKUYYEyZkCX5RZgJMLdsrDJSCyZNkP8="
  - secure: "sXeRdG/I8wAnHsQBDDQasd3Crd+6o1MMjyBFQ1QzKePYGlhZ9Lnqinwu5xwcDM8uWvollooafcdNwQCtVGbHNKELPlGXK7amFkHljwJdrHdTfgW82NUxWykv+ZFy3ffyQkB+f5MQgyRgZpmfBaw2qwAB14FIAxSpfqEph9lC/mMj0TQTL5Fh4Ke2j41vmCECdorlz9LtmNthSf2zvUg6jr8VlNQaXcsgDyIlelB6I5a9xSGQRfr1u2EyGXn0LhWZXqhVyAm1a1ukubzdfOaN5WT2NAZXepUfOQcVcHzzCpHnTIMEcUkWrfx9dEzbsNrYoWYt0g9TExkxrJPyt6wB4iUhjRXXxeS1/LgsIaMRhrRLik8Wdx+Hflq33n13SN2c4TTmXVU8qest0cMCm0PG53dl2zZK4rCdoUOKzncn8RXdbRsNGA4emM5cxk5xrfaqLVsxalv6L5C/FHQu1tDnsflMWVeipeqokoVbiqldp1r9EUYd6gQjSI4cuiZENAvrdK2caiaHR72bGUzsV2vrB5xTHJVkdJq80HlWAuuuvoSlCrI39lMjFjakJWo7hZ3NI83EXLyMEqFqX+5oYxYwxCQgXp3nq70SFSyLKNG9bRGf+2PI/G/Oc69Vb17qD83NL1cnJhnsnKJS350oI42PRFmSDC/yuOlohHHk3aiX9fs="

sudo: required
services:
  - docker


before_install:
  # Build Alfresco micro-services
  - docker-compose up --build -d
  # Build Alfresco slim
  - docker build -f slim/Dockerfile -t ${REG}:${COMMIT} slim/
  - docker run --name 'mysql' -d -p 32731:3306 -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=alfresco -e MYSQL_USER=alfresco -e MYSQL_PASSWORD=secret mysql --character-set-server=utf8 --collation-server=utf8_general_ci --max_connections=1024
  - docker run --name 'alfresco' -d -p 32732:8080 --link mysql:mysql ${REG}:${COMMIT}
  - docker ps -a


script:
  # Wait for alfresco to start
  - sleep 300
  - DOCKER_REPO=`docker ps -qa -f ancestor=${REG}:repository`
  - DOCKER_OOO=`docker ps -qa -f ancestor=${REG}:libreoffice`
  - DOCKER_SEARCH=`docker ps -qa -f ancestor=${REG}:search`
  - DOCKER_SHA=`docker ps -qa -f ancestor=${REG}:share`
  - DOCKER_ALF=`docker ps -qa -f ancestor=${REG}:${COMMIT}`
  # Show logs
  - docker logs $DOCKER_REPO
  - docker logs $DOCKER_OOO
  - docker logs $DOCKER_SEARCH
  - docker logs $DOCKER_SHA
  - docker logs $DOCKER_ALF
  # -i, --include – include protocol headers in the output (H/F)
  # -X, --request – specify request  COMMAND (GET, PUT, DELETE…)  to use
  - docker exec ${DOCKER_ALF} /bin/bash -c "curl -i -X GET -u admin:admin http://localhost:8080/alfresco/service/api/audit/control"
  - docker exec ${DOCKER_OOO} /bin/bash -c "nc -zv -w 5 localhost 8100"
  - docker exec ${DOCKER_SEARCH} /bin/bash -c "curl -i -X GET http://localhost:8983/solr/admin/cores"
  - docker exec ${DOCKER_REPO} /bin/bash -c "curl -i -X GET -u admin:admin http://localhost:8080/alfresco/service/api/audit/control"
  - docker exec ${DOCKER_SHA} /bin/bash -c "curl -iL -X GET -u admin:admin  http://localhost:8080/share/page"
  # Container inter-networking test
  - docker exec ${DOCKER_REPO} /bin/bash -c "nc -zv -w 5 ${DOCKER_OOO} 8100"
  - docker exec ${DOCKER_REPO} /bin/bash -c "curl -i -X GET http://${DOCKER_SEARCH}:8983/solr/admin/cores"
  - docker exec ${DOCKER_SEARCH} /bin/bash -c "curl -i -X GET -u admin:admin http://${DOCKER_REPO}:8080/alfresco/service/api/audit/control"
  - docker exec ${DOCKER_SHA} /bin/bash -c "curl -i -X GET -u admin:admin http://${DOCKER_REPO}:8080/alfresco/service/api/audit/control"
  - curl -iL -X GET -u admin:admin http://localhost:8080/share/page
  - curl -iL -X GET -u admin:admin http://localhost:32732/share/page



after_success:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker tag ${REG}:${COMMIT}-repository ${REG}:${REPO}
  - docker tag ${REG}:${COMMIT}-repository ${REG}:travis-${TRAVIS_BUILD_NUMBER}-repository
  - docker tag ${REG}:${COMMIT}-libreoffice ${REG}:${OOO}
  - docker tag ${REG}:${COMMIT}-libreoffice ${REG}:travis-${TRAVIS_BUILD_NUMBER}-libreoffice
  - docker tag ${REG}:${COMMIT}-search ${REG}:${SEARCH}
  - docker tag ${REG}:${COMMIT}-search ${REG}:travis-${TRAVIS_BUILD_NUMBER}-search
  - docker tag ${REG}:${COMMIT}-share ${REG}:${SHA}
  - docker tag ${REG}:${COMMIT}-share ${REG}:travis-${TRAVIS_BUILD_NUMBER}-share
  - docker tag ${REG}:${COMMIT} ${REG}:${TAG}
  - docker tag ${REG}:{$COMMIT} ${REG}:travis-${TRAVIS_BUILD_NUMBER}
  - docker push ${REG}