apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-db
  labels:
    type: local
    app: alfresco
    tiers: database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data1/alfresco-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-dblog
  labels:
    type: local
    app: alfresco
    tiers: database
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/alfresco-dblog
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-data
  labels:
    type: local
    app: alfresco
    tiers: engine
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/alfresco-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-log
  labels:
    type: local
    app: alfresco
    tiers: engine
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/alfresco-log
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-search-alfresco
  labels:
    type: local
    app: alfresco
    tiers: search
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/alfresco-search-alfresco
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-search-archive
  labels:
    type: local
    app: alfresco
    tiers: search
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/alfresco-search-archive
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-search-contentstore
  labels:
    type: local
    app: alfresco
    tiers: search
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/alfresco-search-contentstore