##########################################################################
# PostgreSQL
##########################################################################
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: alfresco
    tiers: database
spec:
  type: Cluster-IP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: alfresco
    tiers: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-db
  labels:
    app: alfresco
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-dblog
  labels:
    app: alfresco
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
        tiers: database
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_DB
          value: alfresco
        - name: POSTGRES_USER
          value: alfresco
        # $ kubectl create secret generic postgres-pass --from-file=alfresco.postgres.password.txt
        # make sure postgres.password.txt does not have a trailing newline
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alfresco-pass
              key: alfresco.postgres.password.txt
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: alfresco-db
          mountPath: /var/lib/postgresql/data
        - name: alfresco-dblog
          mountPath: /var/log/postgresql
      volumes:
      - name: alfresco-db
        persistentVolumeClaim:
          claimName: alfresco-db
      - name: alfresco-dblog
        persistentVolumeClaim:
          claimName: alfresco-dblog
---
##########################################################################
# Alfresco Search Services
##########################################################################
apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    app: alfresco
    tiers: search
spec:
  type: Cluster-IP
  ports:
  - name: solr-http
    port: 8983
    targetPort: 8983
    protocol: TCP
  selector:
    app: alfresco
    tiers: search
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: alfresco
  name: alfresco-search-alfresco
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: search
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: alfresco
  name: alfresco-search-archive
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: search
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: alfresco
  name: alfresco-search-contentstore
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
        tiers: search
    spec:
      containers:
      - image: fjudith/alfresco:search
        name: search
        ports:
        - containerPort: 8983
          name: solr-http
        volumeMounts:
        - name: alfresco-search-alfresco
          mountPath: /usr/share/alfresco-search-services/solrhome/alfresco
        - name: alfresco-search-archive
          mountPath: /usr/share/alfresco-search-services/solrhome/archive
        - name: alfresco-search-contentstore
          mountPath: /usr/share/alfresco-search-services/contentstore
      volumes:
      - name: alfresco-search-alfresco
        persistentVolumeClaim:
          claimName: alfresco-search-alfresco
      - name: alfresco-search-archive
        persistentVolumeClaim:
          claimName: alfresco-search-archive
      - name: alfresco-search-contentstore
        persistentVolumeClaim:
          claimName: alfresco-search-contentstore
---
##########################################################################
# Libreoffice Services
##########################################################################
apiVersion: v1
kind: Service
metadata:
  name: libreoffice
  labels:
    app: alfresco
    tiers: converter
spec:
  type: Cluster-IP
  ports:
  - name: libreoffice
    port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    app: alfresco
    tiers: converter
  type: Cluster-IP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
        tiers: converter
    spec:
      containers:
      - image: fjudith/alfresco:libreoffice
        name: libreoffice
        ports:
        - containerPort: 8100
          name: libreoffice
---
##########################################################################
# Alfresco Content Repository
##########################################################################
apiVersion: v1
kind: Service
metadata:
  name: repository
  labels:
    app: alfresco
    tiers: engine
spec:
  type: Cluster-IP
  ports:
  - name: netbios-ns
    port: 137
    targetPort: 137
    protocol: UDP
  - name: netbios-dgm
    port: 138
    targetPort: 138
    protocol: UDP
  - name: netbios-ssn
    port: 139
    targetPort: 139
    protocol: TCP
  - name: ftp
    port: 21
    targetPort: 21
    protocol: TCP
  - name: microsoft-ds
    port: 445
    targetPort: 445
    protocol: TCP
  - name: http-proxy
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: alfresco
    tiers: engine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: alfresco
  name: alfresco-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: engine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: alfresco
  name: alfresco-log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      app: alfresco
      tiers: engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repository
  labels:
    app: alfresco
    tiers: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
        tiers: engine
    spec:
      containers:
      - image: fjudith/alfresco:repository
        name: alfresco
        env: 
        - name: DB_KIND
          value: postgresql
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: alfresco
        - name: DB_USERNAME
          value: alfresco
        # $ kubectl create secret generic postgres-pass --from-file=alfresco.postgres.password.txt
        # make sure postgres.password.txt does not have a trailing newline
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alfresco-pass
              key: alfresco.postgres.password.txt
        - name: OOO_ENABLED
          value: "true"
        - name: OOO_HOSTNAME
          value: "libreoffice"
        - name: OOO_PORT
          value: "8100"
        - name: SOLR_INDEX_SUBSYSTEM
          value: "solr6"
        - name: SOLR_HOST
          value: "search"
        - name: SOLR_PORT
          value: "8983"
        ports:
        - containerPort: 137
          name: netbios-ns
        - containerPort: 138
          name: netbios-dgm
        - containerPort: 139
          name: netbios-ssn
        - containerPort: 21
          name: ftp
        - containerPort: 445
          name: microsoft-ds
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
        - name: alfresco-data
          mountPath: /var/lib/alfresco/alf_data
        - name: alfresco-log
          mountPath: /usr/share/tomcat/logs
        livenessProbe:
          tcpSocket:
              port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
      volumes:
      - name: alfresco-data
        persistentVolumeClaim:
          claimName: alfresco-data
      - name: alfresco-log
        persistentVolumeClaim:
          claimName: alfresco-log
---
##########################################################################
# Alfresco Share
##########################################################################
apiVersion: v1
kind: Service
metadata:
  name: share
  labels:
    app: alfresco
    tiers: frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: alfresco
    tiers: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: share
  labels:
    app: alfresco
    tiers: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
        tiers: frontend
    spec:
      containers:
      - image: fjudith/alfresco:share
        name: share
        env:
        - name: ALFRESCO_HOST
          value: repository
        - name: ALFRESCO_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
##########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /share
        backend:
          serviceName: share
          servicePort: 8080
      - path: /alfresco
        backend:
          serviceName: alfresco
          servicePort: 8080
