apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-db
  namespace: alfresco
  labels:
    app: alfresco
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-search-alfresco
  namespace: alfresco
  labels:
    app: alfresco
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-search-archive
  namespace: alfresco
  labels:
    app: alfresco
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-search-contentstore
  namespace: alfresco
  labels:
    app: alfresco
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-data
  namespace: alfresco
  labels:
    app: alfresco
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
